### ISSUE TITLE
feature request (maybe doc update?)

### ISSUE THREAD

**Issue by ltaulell** [suizokukan/katal#43]
I have a feature request (or a doc update request, if it's already possible):

I need an option to create the files database without copying/moving any (selected) files from srcdir to targetdir.

I'll explain myself:
- I (some of my users) have huge collections of files (more than 100TB, more than billions directories and files).
  One of our workflow take hdf5 files (mostly stars simulations) to generate a movie file, then a contact sheet and a thumbnail.
  This highly automated workflow, fail from time to time for reasons. And we have... difficulties to find which movie/contact or thumbnail have failed to generate (due to the very large amount of dir/files).
- Other example:
  Some users deals with genetic data, one sequenced genome has to be stored in various formats. Finding duplicates, failed transferts, failed conversions... is a task by itself.

As a backend task, I may have to search duplicates (but with another filename), purge old backups, etc.

So, having a regulary updated database at the root of a subdir hierarchy, which could be questioned in various way, could be very usefull.
Katal can be that tool (and easely be integrated in our workflows, as an error detector, or final report complement...) if it doesn't have to copy the whole file/dir hierarchies.

Bests

**Comment by suizokukan** [comment]
A very interesting feature ! Thank you for this idea : it's clearly not the way I was supposed to extend Katal but I think it would be interesting to modify my project as a "mirror database" of a source directory. If i'm lucky, the only highly impacted function would be the "fill_select__checks()" one but I have to check this point once again. I'll give you more informations as soon as possible.

**Comment by ltaulell** [comment]
Yes, your project is the lightest and "monolithic-est" :o) for our needs (and in python, and highly adaptable, and well written, and...). 

As an HPC/BigData administrator, I think the needs are just awakening.

**Comment by suizokukan** [comment]
Thank you very much :) I'm already l working on a "--mirroronly" option and I have to test it thoroughly.

Some caveats : 
- I never tested Katal for more than 100.000 files in a source directory; I don't know what would happen with something as big as 100TB of source files ! I can't even guess what may happen !
- Katal uses sqlite3 databases since sqlite3 is supported out-of-the-box by Python; it's maybe the worst database available and I should consider adding a PostgreSql support...
- Katal is slow, very slow : I could speed up my project by reducing the amount of console messages but the core is absolutely inefficient.
- and last but no least... Katal isn't immune to unexpected shutdowns/programs' stops. If you're interested, I may completely rewrite Katal to add "intended tasks" to a queue and to leave a trace of the jobs done/to-be-done/half done/.

Are you in hurry ? I planned to add some documentation (=how the program works) and the --mirroronly option for the next release, may in one week. The last point (intended jobs in a queue) was planned for July.

**Comment by ltaulell** [comment]
Cool,
- tests cases: I have plenty (and not photos collections :o)
- sqlite/postgres: Can't say at the moment :) (but I have both mysql and postgresql servers up&ready)
- speed: Not (really) a problem (most of our "management tools" are shell/python based)
- logs: Add --quiet/--shutup/--reallyshutthefuckup option ? :o)
- Jobs management shouldn't be katal problem.  Or it's own tasks ? Or you mean be managed by a job scheduler (like one's on clusters) ?
- Not in a hurry at all :o)

**Comment by suizokukan** [comment]
Still working on the --mirroronly option. Meanwhile, I thought to the effect of 100TB of data to be read and I realized such an amount of files would create enormous log files. The last version of Katal (0.2.4, see 363d38ed4f2680fcccdb7b69c7b6b28a8a81de09) slices logfiles if they become too big, the limit being defined in katal.ini by the "[log file]maximal size" constant .

**Comment by suizokukan** [comment]
0.2.9 out : I choosed to add replace --mirroronly and --move options by a single option named 'mode'. Now we have --mode=[copy|move|mirror] . It works, but I'm not satisfied with this method : every time the user adds some files in the database, he has to use the --mode option on the command line.

It would be much easier to create a database with a mode value; e.g., a database created with --mode=mirror would never try to copy or to move the source files filling the database; without adding --mode=mirror on each invocation to Katal, the script would automatically use the mirror mode.
 It's not complicated but I have to change the database structure and I need more time, maybe two weeks.

**Comment by ltaulell** [comment]
On 19/01/2016 16:05, Faure Xavier wrote:

> 0.2.9 out : I choosed to add replace --mirroronly and --move options by
> a single option named 'mode'. Now we have --mode=[copy|move|mirror] . It
> works, but I'm not satisfied with this method : every time the user adds
> some files in the database, he has to use the --mode option on the
> command line.
> 
> It would be much easier to create a database with a mode value; e.g., a
> database created with --mode=mirror would never try to copy or to move
> the source files filling the database; without adding --mode=mirror on
> each invocation to Katal, the script would automatically use the mirror
> mode.

Why not in the config file (katal.ini) ?

Maybe 'mirror' is not the best word for this database-only mode.

dbonly? nocopy?

> It's not complicated but I have to change the database structure and I
> need more time, maybe two weeks.

I'm not in a hurry.

## Regards, Loïs

Pôle Scientifique de Modélisation Numérique
 http://www.ens-lyon.fr/PSMN/

**Comment by suizokukan** [comment]
"Why not in the config file (katal.ini) ? " : ok, good idea .
"nocopy" : ok, another good idea :)

Regards, Xavier .

**Comment by suizokukan** [comment]
0.3 out : the mode (copy/move/nocopy) is now defined in the configuration file; your idea allows not to modify the database structure, which is easier and faster to implement as my original idea.
Everything seems ok but I need to test this version thoroughly, e.g. on Windows system and with more source files. I'll give you more informations as soon as possible.

**Comment by suizokukan** [comment]
I fixed the 'iname'/'name' jumbling in katal.ini, thank you. (commit f5ac32742e522a8b5de1137694c962f2f293cc44) .

**Comment by suizokukan** [comment]
0.3.2 (7e22a95606551807ac2692e92f6f45e533f064d0) out : the --mute argument has been replaced by the --verbosity argument, controlling the **console** verbosity. Three possibilities :
- 'none'=no output to the console, no question asked on the console;
- 'normal'=messages to the console and questions asked on the console; 
- 'high'=display discarded files (default: none)

The default level of verbosity being 'normal', no more dull messages are displayed on the console, allowing to speed up execution.

**Comment by suizokukan** [comment]
I close this thread since the _nocopy_ mode has been added and tested. Fell free to open another thread for another request/issue.
