### ISSUE TITLE
tests/data1 : c.5 / C.5 : problem with OSX !

### ISSUE THREAD

**Issue by suizokukan** [suizokukan/katal#50]

**Comment by ltaulell** [comment]
Error in config file :

```
# another examples : 
#       iname : ^c.5$   -> only "c.5"
#       name : ^c.5$   -> only "c.5" and "C.5"
```

It's the opposite (as in find)

**Comment by suizokukan** [comment]
I fixed the 'iname'/'name' jumbling in katal.ini, thank you. (commit f5ac327) .

**Comment by suizokukan** [comment]
I close the issue : tests have to be runned on a Linux-like system, as mentioned in the documentation.
